name: modern_charts
version: 0.1.0
author: Man Hoang <jolleekin@outlook.com>
description: A lightweight package for creating modern charts in Dart.
homepage: https://github.com/jolleekin/modern_chart
dependencies:
  intl: any
dev_dependencies:
  browser: any
